### ISSUE TITLE
Missing release : apache-livy-0.8.0-incubating-1.0_2.12-bin.zip

### ISSUE THREAD

**Issue by alexismarie8314** [TOSIT-IO/incubator-livy-old#2]
Hello, 
I am raising this issue because I cannot found the version "apache-livy-0.8.0-incubating-1.0_2.12-bin.zip"

Thank you.

**Comment by PACordonnier** [comment]
@rpignolet if you have the binary somewhere is it possible for you to upload it in a new release ? Thanks !

**Comment by rpignolet** [comment]
https://github.com/TOSIT-IO/incubator-livy-fork/releases/tag/0.8.0-incubating-1.0

**Comment by PACordonnier** [comment]
Perfect thank you
